name: Versioning

on:
  push:
    branches:
      - master  # Modify this according to your branch name

permissions: write-all

jobs:
  versioning:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14  # Modify this according to your Node.js version requirements

      - name: Install dependencies
        run: npm install lerna

      - name: Initialize lerna
        run: npx lerna init

      - name: Commit changes
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add package-lock.json package.json
          git commit -m "Committing changes before versioning"

      - name: Lerna versioning
        run: npx lerna version --conventional-commits --yes 

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: ${{ github.ref }}
          tags: true
          github_token: ${{ secrets.PAT_GITHUB2 }}
